name: CI/CD Workflow with Comprehensive Testing

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Optionally, install dependencies if your testing tools require them
      - name: Install dependencies
        run: npm install

      # Link Checking
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: --accept 200,403,429 https://example.com

      # HTML Validation
      - name: Validate HTML
        run: npx html-validator-cli --url https://example.com --format text

      # CSS Validation
      - name: Lint CSS (stylelint)
        run: npx stylelint "**/*.css"

      # JavaScript Linting
      - name: Lint JavaScript (ESLint)
        run: npx eslint .

      # Deploy to S3 (assuming previous steps passed)
      - name: Deploy to S3
        run: aws s3 sync build/ s3://laskaridissa.com --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'

      # Performance Testing with Lighthouse
      - name: Performance Testing with Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://example.com
          uploadArtifacts: true

