name: Deploy Website to Amazon S3

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1  # Adjust your AWS region as necessary

    - name: Delete contents of the S3 bucket
      run: aws s3 rm s3://laskaridissa.com --recursive

    - name: Adjust directory structure (if necessary)
      run: |
        # Your commands to adjust the directory structure go here
        # This step is optional and depends on your project's specific needs

    - name: Deploy to S3
      run: aws s3 sync . s3://laskaridissa.com --delete
      # The sync command now starts from the current directory ('.')
      # Adjust the source directory if your site's files are in a subdirectory.

    - name: Verify deployment
      run: |
        # Optional: Commands to verify your deployment could be added here.
        # This could include checking for the presence of certain files in the bucket or ensuring the site is responding as expected.
